### PR TITLE
Remove nmake port of harfbuzz

### LINKED ISSUE #479: Remove win32/ folder and direct nmake support
First of all I should mention that all @fanc999 works on harfbuzz project is highly appreciated on providing nmake and that was very helpful on making cmake port also happen (namely and used on CMake port items, the creation and separation of Makefile.sources and annotating harfbuzz API with HB_EXPORT, and probably much more I am just missing).

As just a suggestion, now that we have cmake port in and that is able to generate nmake build files also, I like to just propose removal of nmake support and win32 folder entirely from harfbuzz project. I think cmake is just easier to use for Windows people as its better integration with Visual Studio (also even better with [native vs support](https://blogs.msdn.microsoft.com/vcblog/2016/10/05/cmake-support-in-visual-studio/)) and this will reduce maintenance load of harfbuzz project and less confusion of people want to use harfbuzz on their Windows projects.

I should mention however gir/gobject implementation of the cmake port is just not done yet and I probably wouldn't able to reach to it as lack of experience on it, but I am also not sure how much that would be needed for third party projects that was provided on nmake port, and there are possibly more needed tweaks for our just new and early cmake to make it really useful for other projects which probably @fanc999 knows better than me so there is no rush on this and there is also a chance this will be just closed if we conclude removing nmake is not a good move for harfbuzz project. Thanks all.

### PR DESCRIPTION
**Pull request by ebraminio**
Closes #479 

and as suggested there by Behdad.

This encourages use of cmake but our cmake port lacks gir support for now so that should be considered.

As a note for Windows users, please consider just using https://github.com/Microsoft/vcpkg which builds harfbuzz for you among many other libraries and don't get involve with the detail of building harfbuzz thus asking support here.

### CODE REVIEW

**Comment by ebraminio** [comment]
@Behdad, I guess you should consider bumping a minor version at least for the removal.

**Comment by ebraminio** [comment]
We should also put some notice to discourage Windows build bugs something like what is done [here](https://github.com/Homebrew/brew/issues/new) by [this](https://github.com/Homebrew/brew/tree/master/.github) folder.

**Comment by khaledhosny** [comment]
What about GTK Windows builds that I think depend on this, can they use vcpkg?

**Comment by ebraminio** [comment]
> What about GTK Windows builds that I think depend on this, can they use vcpkg?

They should use cmake directly of course but I guess gir is also needed, so no idea honestly.

**Pull request merged**
