### PR TITLE
Add working but less prefect DirectWrite backend

### PR DESCRIPTION
**Pull request by ebraminio**
More description on this mailing list [post](http://lists.freedesktop.org/archives/harfbuzz/2015-September/005062.html).

### CODE REVIEW

**Comment by ebraminio** [comment]
Squashed.

Behdad, this is far from prefect but may I suggest putting this on some branch?

On anycase, I am open for your code reviews, at least for reaching to a point suitable for having it on a branch, so please have a look at.

**Comment by KrasnayaPloshchad** [comment]
Since M$ making DirectWrite more competitiveness with Uniscribe, and more apps tend to use DirectWrite, the developments on `hb-directwrite` is necessary.

**Comment by khaledhosny** [comment]
Since Uniscribe seems to be just a backward compatibility wrapper around DirectWrite these days, do we gain much be using DirectWrite directly? After all these backends are just for testing and comparing HarfBuzz output to Uniscribe and nothing else.

**Comment by KrasnayaPloshchad** [comment]
Eh, I got wrong materials about DirectWrite, sorry.

**Comment by ebraminio** [comment]
Studying DW API given for Kashida justification was my only motivation for this which I am not saying is even a good one. I don't think I am the right person for this even as the lack of enough familiarity with Windows APIs and the fact that honestly I couldn't even find any clean solution on using mingw/cygwin autotools with directx API headers and actually I used a cmake build script with vs for this. However I hope this would be useful thing for further attempts at someday.

**Comment by behdad** [comment]
Should add buildsystem support for this.  I'll give it a try when I have my Windows 10 machine around.

**Comment by ebraminio** [comment]
Oh, thank you Behdad. I see this as a great step forward. As its known issues I explained on ML I was expecting see this on a branch moreover but this is even better. I doubt there would be any clean way to use dx headers with autotools system but the WIP NMake support seems is fixing this issue also finally.

One suggestion, to prevent misuse of clients from the dx support for now, I think it would be nice to put some compiler directive (maybe `#warning`?) to indicate this is not for use for now. Perhaps that would be useful till I could get access to a machine or someone more familiar with dx and this particular thing could resolve the issues.

Thank you

**Comment by behdad** [comment]
As long as it's not easy to build with it, we should be fine.  But feel free to send a PR.

**Comment by fanc999** [comment]
Hi,

For references, I have it in a commit in PR #164 integration in the autotools build system, which I managed to do successfully with MSYS2/mingw-w64.

With blessings!

**Pull request merged**
