### PR TITLE
Add a dummy CircleCI config on gh-pages branch

### PR DESCRIPTION
**Pull request by ebraminio**

### CODE REVIEW

**Comment by ebraminio** [comment]
@behdad @khaledhosny, Travis bot removed "circle.yml", https://github.com/behdad/harfbuzz/commit/ecc784d6b00098d9dc9d3df579f946575987983f what should we do?

**Comment by anthrotype** [comment]
The War of the Bots :robot:

**Comment by behdad** [comment]
Hahahaha.  Check .ci/deploy-docs.sh

**Comment by ebraminio** [comment]
Ok, I hope #602 works.

**Comment by ebraminio** [comment]
Hmm, didn't work https://github.com/behdad/harfbuzz/commit/d940b85ae7a18ce8a298288cf6ca1b99e7158a4c

**Comment by ebraminio** [comment]
Hmm, something like this https://github.com/behdad/harfbuzz/blob/master/docs/Makefile.am#L69 should be added for "circle.yml"? Not familiar with gtkdocize, can you fix this Behdad?

**Comment by ebraminio** [comment]
Somehow hack, #603

**Comment by behdad** [comment]
Your hack is exactly how I would do it.

**Comment by ebraminio** [comment]
It makes sense, thanks. I felt it was better if I was embedding the configuration inside the script or move it somewhere else but anyway no longer build issues https://circleci.com/gh/behdad/harfbuzz

**Pull request merged**
