### PR TITLE
[coretext] Speculative fix for CoreText nullptr access

### PR DESCRIPTION
**Pull request by ebraminio**
Merge back of a committed on Chromium patch: https://codereview.chromium.org/2118263002/

### CODE REVIEW

**Comment by ebraminio** [comment]
Additionally, I put some spaces here and there in order to conform more with harfbuzz code style.

**Comment by ebraminio** [comment]
Interesting that I can not use coretext backend without the patch on even simplest cases so it is not just speculative for me at least.

**Comment by drott** [comment]
So the patch fixes this for you? Which Mac OS version, Sierra?

LGTM for merging this.

**Comment by ebraminio** [comment]
Yes. Actually it is an El Capitan, 10.11.3.

**Comment by ebraminio** [comment]
Do you think it would be better to remove some of you comments there? BTW, I've profiled and inspected more on memory usage of the backend and fixed [one of the issues](https://github.com/ebraminio/harfbuzz/commit/5462882e807107bcd4d7bf7844b46c7ef92c603a). Does the fix sounds right to you?

**Pull request merged**
