### PR TITLE
[ci] Add CircleCI for cross-compiling

### PR DESCRIPTION
**Pull request by ebraminio**
Part of #589

@behdad, you should login into http://circleci.com and enable it for harfbuzz but before that, do you have any idea why this is happening on some compilers? Have a look at [this](https://circleci.com/gh/ebraminio/harfbuzz/tree/master) for more info.

```
[31/41] Building CXX object CMakeFiles/harfbuzz.dir/src/hb-ot-font.cc.o
FAILED: CMakeFiles/harfbuzz.dir/src/hb-ot-font.cc.o 
/usr/arm-linux-androideabi/bin/arm-linux-androideabi-g++ --sysroot=/usr/arm-linux-androideabi/sysroot  -DHAVE_FALLBACK -DHAVE_INTEL_ATOMIC_PRIMITIVES -DHAVE_OT -DHAVE_UCDN -I../src -Isrc -I../src/hb-ucdn  -MD -MT CMakeFiles/harfbuzz.dir/src/hb-ot-font.cc.o -MF CMakeFiles/harfbuzz.dir/src/hb-ot-font.cc.o.d -o CMakeFiles/harfbuzz.dir/src/hb-ot-font.cc.o -c ../src/hb-ot-font.cc
In file included from ../src/hb-ot-post-table.hh:31:0,
                 from ../src/hb-ot-font.cc:41:
../src/hb-sort-r.hh: In function 'void hb_sort_r(void*, size_t, size_t, int (*)(const void*, const void*, void*), void*)':
../src/hb-sort-r.hh:247:46: error: 'qsort_r' was not declared in this scope
         qsort_r(base, nel, width, compar, arg);
                                              ^
```

### CODE REVIEW

**Comment by behdad** [comment]
Yes, I commented the prototype for `qsort_r` so as not to duplicate it.  Let me define `_GNU_SOURCE`.

**Comment by ebraminio** [comment]
Please make sure it will work on Visual C also https://ci.appveyor.com/project/behdad/harfbuzz/build/1.0.701/job/yeg17r37a9ledfv4#L473

**Comment by behdad** [comment]
Enabled.

**Comment by ebraminio** [comment]
Rebased and still https://circleci.com/gh/ebraminio/harfbuzz/tree/master

```
FAILED: CMakeFiles/harfbuzz.dir/src/hb-ot-font.cc.o 
/usr/arm-linux-androideabi/bin/arm-linux-androideabi-g++ --sysroot=/usr/arm-linux-androideabi/sysroot  -DHAVE_FALLBACK -DHAVE_INTEL_ATOMIC_PRIMITIVES -DHAVE_OT -DHAVE_UCDN -I../src -Isrc -I../src/hb-ucdn  -MD -MT CMakeFiles/harfbuzz.dir/src/hb-ot-font.cc.o -MF CMakeFiles/harfbuzz.dir/src/hb-ot-font.cc.o.d -o CMakeFiles/harfbuzz.dir/src/hb-ot-font.cc.o -c ../src/hb-ot-font.cc
In file included from ../src/hb-ot-post-table.hh:31:0,
                 from ../src/hb-ot-font.cc:41:
../src/hb-sort-r.hh: In function 'void hb_sort_r(void*, size_t, size_t, int (*)(const void*, const void*, void*), void*)':
../src/hb-sort-r.hh:247:46: error: 'qsort_r' was not declared in this scope
         qsort_r(base, nel, width, compar, arg);
                                              ^
```

It think you can go ahead and enable circleci.

**Comment by ebraminio** [comment]
Added our new badge also :) I don't know why we don't see it yet

**Comment by ebraminio** [comment]
@behdad, I guess yiu should start the ci or something like that as the badge on readme.

**Comment by behdad** [comment]
Ok I'll get rid of the qsort_r.

**Comment by behdad** [comment]
In the queue.

**Comment by ebraminio** [comment]
One intresting thing to note, circleci provides SSH access to Ci machines, you can use it when you want access the environment harfbuzz build fails.

**Comment by ebraminio** [comment]
Also I should note we are not limited to crossdock images, you can find and even create and host freely on dockerhub your own images for testing more environments.

**Comment by ebraminio** [comment]
Also feel free to change cmake build of this ci config to autotools, I just found using cmake easier. I didn't test auxilary harfbuzz thinga like hb-ft as they need separate compile of other libraries also but feel free to do so if you found easier way.

**Comment by behdad** [comment]
I don't care about cmake or not, but do care about running tests if possible.  Though, just building is indeed better than nothing. Thanks.  Oh wait, these are all cross-builds, so we cannot test, right?  Then cmake is as good as any.  Thanks!

**Comment by behdad** [comment]
Any idea why arm64 is failing:
```
Error response from daemon: repository dockcross/android-arm64 not found: does not exist or no pull access
```

Also, can you somehow configure it to not try building gh-pages branch?

**Comment by ebraminio** [comment]
> Also, can you somehow configure it to not try building gh-pages branch?

https://circleci.com/docs/2.0/configuration-reference/#branches

```
branches:
  ignore:
    - gh-pages
```

would do that I guess.

**Comment by behdad** [comment]
Thanks.

**Pull request merged**
