### PR TITLE
[ci] Add Fedora builder

### PR DESCRIPTION
**Pull request by ebraminio**
As https://github.com/behdad/harfbuzz/issues/589#issuecomment-341161406 I thought adding a fedora based compile also would be nice. Unlike others, this does `make check` also.

### CODE REVIEW

**Comment by behdad** [comment]
Thanks!

BTW, I'm still getting emails re gh-pages.

**Comment by ebraminio** [comment]
There is a possible fix here #596 but I am not sure about it, it is ignoring top level branch filter and is a bug it seems, couldn't follow the documentations.

**Comment by behdad** [comment]
Looks like the `yum`-based ones need '-y' to be passed to yum.  It's waiting for user to confirm installation and times out I think. https://circleci.com/gh/ebraminio/harfbuzz/111

**Comment by ebraminio** [comment]
My attention there was on `No package pkg-config available. No package ragel available.` I added -y later.

**Comment by ebraminio** [comment]
@behdad, Hmm, asked [here](https://discuss.circleci.com/t/excluding-a-branch-from-ci/17811) but I guess you should put a dummy .circleci/config.yml

**Comment by behdad** [comment]
Works for me.

**Comment by ebraminio** [comment]
Done on #599

**Pull request merged**
