### PR TITLE
Minor refactoring to the atomics implementation

### PR DESCRIPTION
**Pull request by KonstantinRitt**

### CODE REVIEW

**Comment by behdad** [comment]
Thanks.  I implemented the first two commits in a different way.

**Comment by behdad** [comment]
Thanks.  I merged this after minor changes.  Please check.

**Comment by KonstantinRitt** [comment]
LGTM so far. Thanks.

**Comment by KonstantinRitt** [comment]
missing HB_ATOMIC_INT_IMPL_INIT definition in 
#elif !defined(HB_NO_MT) && (defined(_WIN32) || defined(__CYGWIN__))
section

**Comment by behdad** [comment]
Fixed.  Thanks.

**Pull request closed without merging**
