### PR TITLE
Introduce get_extent support for color bitmap font.

### PR DESCRIPTION
**Pull request by nona-google**
hb_font_get_glyph_extents now works for color bitmap fonts. Currently
only font having index format 1 and image format 17 is supported.

### CODE REVIEW

**Comment by nona-google** [comment]
I uploaded without unit tests since I couldn't find an example of unit tests with real font file for hb_font_*** API.

Please take a look.
Thank you.

**Comment by behdad** [comment]
@nona-google, do you still need this given FreeType patch?  I still want to get this in, but want to know about priority.  Thanks.

**Comment by nona-google** [comment]
Yes, the situation could be better by the FreeType patch but UI thread is still blocked by PNG decoding.
With this patch, UI thread is no longer blocked by compositor thread during emoji decoding.

I found some bugs on my previous patch. I'm going to upload revised one soon.
Thank you.

**Comment by nona-google** [comment]
Uploaded a patch. Please take a look.
Thank you.

**Comment by nona-google** [comment]
I'm sorry for leaving failing patch. Finally all checks passed. Could you kindly take a look?

Thank you.

**Comment by behdad** [comment]
Thanks nona!  I'm merging and making cosmetic changes on top.

**Pull request merged**
