### PR TITLE
Don't rely on .cluster in _hb_ot_shape_normalize()

### PR DESCRIPTION
**Pull request by jfkthame**
See https://bugzilla.mozilla.org/show_bug.cgi?id=890156

### CODE REVIEW

**Comment by behdad** [comment]
lgtm.  Please merge.  Can you add a micro-test as well?

**Comment by jfkthame** [comment]
I don't have a suitable checkout & dev environment set up to create micro-tests ATM, was hoping you might be able to add those, thx.

**Comment by behdad** [comment]
Will do.  Thanks.

**Comment by behdad** [comment]
It's hard to generate test for this.  So I just merged manually.

**Pull request closed without merging**
