### PR TITLE
Shaping tests for Tibetan vowels

### PR DESCRIPTION
**Pull request by domschl**
This implements tests for Tibetan vowels e, i, u, ei, au, I, U, aH, aM, oM.
Font used is [DDC_Uchen by Chris Fynn (Open Font License)](https://github.com/mozilla-b2g/moztt/tree/master/DDCUchen-1.000)
This test will currently break on U (ཨཱུ), if pull-request #443 is not applied. (Discussion in #417 )

### CODE REVIEW

**Comment by eroux** [comment]
Thanks, that looks good! I think the initial change was to handle some of the weird abbreviations of http://www.babelstone.co.uk/Tibetan/Contractions.html although it's not clear what particular abbreviations were supposed to be handled... maybe you could add a few more things from these abbreviations in the tests? There are also some in http://www.dzongkha.gov.bt/publications/publication_pdf/A%20handbook%20of%20Dzongkha%20and%20Ch%C3%B6k%C3%A9%20abbreviations.pdf but I think only very few specific ones should be picked up

**Comment by domschl** [comment]
I'll have a look and add more tests.
However, to my knowledge, the only application for supporting those shorthands would be to print a text about shorthands ;-) The shorthands were only used in dbu med hand-writings, and -- as far as I know -- are usually always expanded during type-setting.
Anyway, it's useful to find out how the initial change came about, so I will add more tests from those sources...

**Comment by eroux** [comment]
Well, in Dzongkha these shorthands can be frequent, even in dbu can; `དྲགོས` for instance is really considered normal (it's a shorthand for `དྲགོས`)

**Comment by domschl** [comment]
Ah, that I didn't know. 
Can I change contractions.txt? Sometimes, by re-ordering the vowel-signs, the standard shaper could work, e.g. ཀླུ་ཟློག་ can be written as kluog ཀློུག་ (looks ok) or  kloug ུཀློུག་. (looks bad)
Generally, in case of multiple vowels with u, using u first, makes it easier for the shaper.

**Comment by eroux** [comment]
Yes, I suspect this was the original intent of the patch, I think we can probably modify it so that u is always used first, except when there is an achung (which would cause the bug to come back)

**Comment by domschl** [comment]
Hi,
yes, that was most probably what happened.

I started to test with a different rewrite-strategy in hb-unicode-private.hh:
/* Tibetan */
#define HB_MODIFIED_COMBINING_CLASS_CCC129 129 /* sign aa */
#define HB_MODIFIED_COMBINING_CLASS_CCC130 132 /* sign i */
#define HB_MODIFIED_COMBINING_CLASS_CCC132 131 /* sign u */
#define HB_MODIFIED_COMBINING_CLASS_CCC138 133 /* sign e */
#define HB_MODIFIED_COMBINING_CLASS_CCC140 134 /* sign o */

This seems to make the standard vowels and shorthands happy.
I'll test some more...

**Comment by eroux** [comment]
Thanks! interesting, why u before i?

**Comment by domschl** [comment]
if you have ཀིུས་, it's important to shape ཀུ་ first, (because there's a special glyph in the font), and then add the kiku (which doesn't require a custom-glyph). The reordering-rule just tells the shaper, that the sequence kuis is fine. Without the rule, the shaper would not use the glyph for ku, and the result would look smashed.

So basically, it seems the original idea of moving the u-vowel earlier was just the right idea, they just moved it one place too far (in front of achung).

This now just needs *lots* of testing.

**Comment by eroux** [comment]
Oh ok, I was just confused by the fact that the line about i is before the line about u, but the numbers are in the correct order, sorry! I think it should be fine this way! There are indeed many tests to do (although I think you should be able to make all the permutations of all vowels programmatically quite simply), but you're definitely on right tracks, thanks a lot!

**Comment by domschl** [comment]
I checked the output for the 612 entries in contractions.txt, and with:

```
/* Tibetan
 * 
 * In case of multiple vowel-signs, use u first (but after achung) 
 * this allows Dzongkha multi-vowel shortcuts to render correctly 
 */
#define HB_MODIFIED_COMBINING_CLASS_CCC129 129 /* sign aa */
#define HB_MODIFIED_COMBINING_CLASS_CCC130 132 /* sign i */
#define HB_MODIFIED_COMBINING_CLASS_CCC132 131 /* sign u */
#define HB_MODIFIED_COMBINING_CLASS_CCC138 138 /* sign e */
#define HB_MODIFIED_COMBINING_CLASS_CCC140 140 /* sign o */
```

609 Testcases are ok with DDC_Uchen. The missing 3 would require patching DDC_Uchen, because of missing glyphs that cannot be compensated by the shaper (e.g.: rdz+ra) . I am unsure on how many testcases we should add to the automatic tests (I started just adding all of them, when noticing that the other languages just use a few tests)

**Comment by eroux** [comment]
great! let's wait for some input from @behdad or @khaledhosny and see what kind of tests are necessary... I think the minimum would be the U stack and also something like kui... but for me your code is ok, thanks a lot!

**Comment by domschl** [comment]
Ok, I've added a few "best-of-contractions" tests for the multiple-vowel cases that where broken before the new-reordering patch. That way we can check that the "conventional" Tibetan with all vowels work, and that we support the contraction-shortcuts. I guess that's it so far, and let's wait for feed-back.

Reminder: the test for tibetan-vowels.tests will break on checking long-u (ཨཱུ), until #443 is applied.

**Comment by KrasnayaPloshchad** [comment]
I found the following resource is suitable for test:
http://yalasoo.com/English/docs/yalasoo_en_font.html

**Comment by KrasnayaPloshchad** [comment]
> The missing 3 would require patching DDC_Uchen, because of missing glyphs that cannot be compensated by the shaper (e.g.: rdz+ra) .

I suggest you can also try to test with this font:
[himalaya.zip](https://github.com/behdad/harfbuzz/files/871315/himalaya.zip)

**Comment by domschl** [comment]
Good news: MS Himalaya renders all vowel- and contractions-test-cases correctly with the new shaper patch. 
The only cosmetic issue I could find is a slightly irregular rendering of a triple-drengbu vowel-sign, that's sometimes uses as a shortcut for repetitions of three syllables. The three vowel-signs are not quite equidistant:
image
All other testcases (>600) are flawless.

**Comment by behdad** [comment]
Adding all is good if the resulting font is not too big.  Thanks!

**Comment by behdad** [comment]
> I suggest you can also try to test with this font:
> himalaya.zip

Don't post fonts you don't have license to distribute.  I'm going to delete your comment.

**Comment by domschl** [comment]
All 600 test-cases require a subset-font that is 384kB (the original complete DDC_Uchen is 861kB).

Would that be too large? If yes, what would be a reasonable upper limit? So far, the largest test-font in the repo is 74kB.

I guess it is possible to make the Tibetan contractions test-set smaller (and less redundant), depending on how big test-fonts-files we want to allow.

**Comment by domschl** [comment]
I've extended the test-cases to cover all 113 cases from texts/in-tree/shaper-tibetan/script-tibetan/misc/contractions.txt that actually use multiple vowel-signs.
Resulting tests have been split into two files to work around size-limitations of hb-view.
The test-font files are about 120kb, 100kb which is quite large.

**Pull request merged**
